compress: true
javascripts:
  jquery: &jquery
    - javascripts/jquery/jquery-1.8.2.js
    - javascripts/jquery/jquery-ui-1.9.1.custom.js
    - javascripts/jquery/jquery.metadata.js
    - javascripts/jquery/jquery.placehold-0.3.js
    - javascripts/jquery/validator.js

  header: &header
    - javascripts/vendor/notificon.js
    - javascripts/header.js
    - javascripts/personal_notifications.js

  toolbar: &toolbar
    - javascripts/toolbar.js
    - javascripts/toolbar-buttonset.js
    - javascripts/smiley-picker.js

  base:
    - *jquery
    - javascripts/underscore.js
    - javascripts/l10n.js
    - javascripts/init.js
    - javascripts/ajax_notifications.js
    - javascripts/url_helper.js
    - javascripts/updater.js
    - javascripts/study_area_selection.js
    - javascripts/dialog_box.js
    - javascripts/file_system.js
    - javascripts/arbeitsgruppen.js
    - javascripts/news.js
    - javascripts/termine.js
    - javascripts/quick_search.js
    - javascripts/multi_select.js
    - javascripts/browse.js
    - javascripts/tabs.js
    - javascripts/audio.js
    - javascripts/calendar.js
    - javascripts/schedule.js
    - javascripts/skip_links.js
    - javascripts/forms.js
    - javascripts/messaging.js
    - javascripts/room_request_dialog.js
    - javascripts/calendar_dialog.js
    - javascripts/old_upload.js
    - javascripts/drag_and_drop_upload.js
    - javascripts/status_group.js
    - javascripts/sem_classes.js
    - *header
    - *toolbar
    - javascripts/application.js

  raumzeit:
    - javascripts/raumzeit.js

  smileys:
    - javascripts/smiley.js

  settings:
    - javascripts/settings.js
css:
  base:
    # filname : media
    jquery-ui-1.9.1.custom.css: screen, print
    jquery-ui-studip.css: screen, print
    style.css:  screen
    smiley.css: screen, print
    print.css:  print
